- name: Makefile CI
  - name: Install Theos
uses: Randomblock1/theos-action@v1.4
            

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run make
      run: make

    - name: Run make packages
      run: make packages
