name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install dependencies
      uses: Randomblock1/theos-action@v1.4

    - name: Run make
      run: make

    - name: Run make packages
      run: make packages
